export type Category = {
  label: string;
  icon: string;
  stocks: { symbol: string; name: string }[];
};

export const CATEGORIES: Category[] = [
  {
    icon: "???",
    label: "Technology",
    stocks: [
      { symbol: "AAPL", name: "Apple" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "META", name: "Meta Platforms" },
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "INTC", name: "Intel" },
      { symbol: "AMD", name: "AMD" },
      { symbol: "ORCL", name: "Oracle" },
    ],
  },
  {
    icon: "??",
    label: "Finance",
    stocks: [
      { symbol: "JPM", name: "JPMorgan Chase" },
      { symbol: "BAC", name: "Bank of America" },
      { symbol: "WFC", name: "Wells Fargo" },
      { symbol: "GS", name: "Goldman Sachs" },
      { symbol: "MS", name: "Morgan Stanley" },
      { symbol: "V", name: "Visa" },
      { symbol: "MA", name: "Mastercard" },
      { symbol: "PYPL", name: "PayPal" },
      { symbol: "BLK", name: "BlackRock" },
      { symbol: "SCHW", name: "Charles Schwab" },
    ],
  },
  {
    icon: "??",
    label: "Healthcare",
    stocks: [
      { symbol: "JNJ", name: "Johnson & Johnson" },
      { symbol: "PFE", name: "Pfizer" },
      { symbol: "MRNA", name: "Moderna" },
      { symbol: "ABBV", name: "AbbVie" },
      { symbol: "MRK", name: "Merck & Co." },
      { symbol: "UNH", name: "UnitedHealth Group" },
      { symbol: "LLY", name: "Eli Lilly" },
      { symbol: "AMGN", name: "Amgen" },
      { symbol: "GILD", name: "Gilead Sciences" },
      { symbol: "CVS", name: "CVS Health" },
    ],
  },
  {
    icon: "???",
    label: "Consumer",
    stocks: [
      { symbol: "WMT", name: "Walmart" },
      { symbol: "TGT", name: "Target" },
      { symbol: "COST", name: "Costco" },
      { symbol: "NKE", name: "Nike" },
      { symbol: "SBUX", name: "Starbucks" },
      { symbol: "MCD", name: "McDonald's" },
      { symbol: "KO", name: "Coca-Cola" },
      { symbol: "PEP", name: "PepsiCo" },
      { symbol: "HD", name: "Home Depot" },
      { symbol: "LOW", name: "Lowe's" },
    ],
  },
  {
    icon: "?",
    label: "Energy",
    stocks: [
      { symbol: "XOM", name: "ExxonMobil" },
      { symbol: "CVX", name: "Chevron" },
      { symbol: "SHEL", name: "Shell" },
      { symbol: "BP", name: "BP" },
      { symbol: "TTE", name: "TotalEnergies" },
      { symbol: "COP", name: "ConocoPhillips" },
      { symbol: "OXY", name: "Occidental Petroleum" },
      { symbol: "ENB", name: "Enbridge" },
      { symbol: "NEE", name: "NextEra Energy" },
      { symbol: "SLB", name: "Schlumberger" },
    ],
  },
  {
    icon: "??",
    label: "Automotive & EV",
    stocks: [
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "F", name: "Ford" },
      { symbol: "GM", name: "General Motors" },
      { symbol: "RIVN", name: "Rivian" },
      { symbol: "LCID", name: "Lucid Motors" },
      { symbol: "TM", name: "Toyota" },
      { symbol: "VWAGY", name: "Volkswagen" },
      { symbol: "RACE", name: "Ferrari" },
      { symbol: "NIO", name: "NIO" },
      { symbol: "XPEV", name: "XPeng" },
    ],
  },
  {
    icon: "??",
    label: "Cloud & SaaS",
    stocks: [
      { symbol: "CRM", name: "Salesforce" },
      { symbol: "ADBE", name: "Adobe" },
      { symbol: "SNOW", name: "Snowflake" },
      { symbol: "NOW", name: "ServiceNow" },
      { symbol: "WDAY", name: "Workday" },
      { symbol: "ZM", name: "Zoom" },
      { symbol: "DBX", name: "Dropbox" },
      { symbol: "TEAM", name: "Atlassian" },
      { symbol: "SHOP", name: "Shopify" },
      { symbol: "TWLO", name: "Twilio" },
    ],
  },
  {
    icon: "??",
    label: "Gaming & Entertainment",
    stocks: [
      { symbol: "NFLX", name: "Netflix" },
      { symbol: "DIS", name: "Disney" },
      { symbol: "RBLX", name: "Roblox" },
      { symbol: "EA", name: "Electronic Arts" },
      { symbol: "TTWO", name: "Take-Two Interactive" },
      { symbol: "WBD", name: "Warner Bros. Discovery" },
      { symbol: "SPOT", name: "Spotify" },
      { symbol: "SONY", name: "Sony" },
      { symbol: "NTDOY", name: "Nintendo" },
      { symbol: "PARA", name: "Paramount Global" },
    ],
  },
  {
    icon: "???",
    label: "Industrials",
    stocks: [
      { symbol: "BA", name: "Boeing" },
      { symbol: "CAT", name: "Caterpillar" },
      { symbol: "GE", name: "General Electric" },
      { symbol: "HON", name: "Honeywell" },
      { symbol: "MMM", name: "3M" },
      { symbol: "UNP", name: "Union Pacific" },
      { symbol: "DE", name: "Deere & Company" },
      { symbol: "LMT", name: "Lockheed Martin" },
      { symbol: "RTX", name: "RTX Corporation" },
      { symbol: "NOC", name: "Northrop Grumman" },
    ],
  },
  {
    icon: "??",
    label: "Telecom & Internet",
    stocks: [
      { symbol: "T", name: "AT&T" },
      { symbol: "VZ", name: "Verizon" },
      { symbol: "TMUS", name: "T-Mobile" },
      { symbol: "CMCSA", name: "Comcast" },
      { symbol: "CHTR", name: "Charter Communications" },
      { symbol: "BIDU", name: "Baidu" },
      { symbol: "BABA", name: "Alibaba" },
      { symbol: "TCEHY", name: "Tencent" },
      { symbol: "SNAP", name: "Snap" },
      { symbol: "PINS", name: "Pinterest" },
    ],
  },
];
